project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: public-goods.qmd
        text: Public Goods
      - href: blogs.qmd
        text: Blogs

format:
  html:
    theme: flatly
    toc: false
    smooth-scroll: true
    anchor-sections: true
    css: styles.css
    highlight-style: github

execute:
  echo: false

metadata-files:
  - _metadata.yml
