project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: public-goods.qmd
        text: Public Goods
      - href: blogs.qmd
        text: Blogs

  page-footer:
    center: |
      Visits: ![](https://visitor-badge.laobi.icu/badge?page_id=AmitKr-GitsHub.AmitKr-GitsHub.github.io)

format:
  html:
    theme: flatly
    toc: false
    smooth-scroll: true
    anchor-sections: true
    css: styles.css
    highlight-style: github
    # Adding the GoatCounter script here ensures it is included in every page header
    include-in-header:
      text: |
        <script data-goatcounter="https://amitkr.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

execute:
  echo: false

metadata-files:
  - _metadata.yml
